### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by josnfei** [6sy/myShop#2]
![image](https://user-images.githubusercontent.com/28798709/82399103-f0889700-9a86-11ea-8497-d6f74213bb8c.png)

router/api/users.js文件是不是漏了？

**Comment by 6sy** [comment]
不好意思，已经解决了。

**Comment by 6sy** [comment]
> ![image](https://user-images.githubusercontent.com/28798709/82399103-f0889700-9a86-11ea-8497-d6f74213bb8c.png)
> 
> router/api/users.js文件是不是漏了？

请拉去上一次提交的版本，不好意思
